version: '3.7'

services:
  web:
    build: .
    command: bash startup.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - PGUSER=${POSTGRES_USER?Variable not set}
      #- POSTGRES_HOST=localhost
    ports:
      - "5432:5432"

volumes:
  postgres_data:
